// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: balance-request.proto
// Protobuf Java Version: 4.32.0

package com.example.protobuf;

@com.google.protobuf.Generated
public final class BalanceProto {
  private BalanceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      BalanceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DailyBalanceRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.DailyBalanceRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string date = 1;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>string date = 1;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>repeated .com.example.TradeEvent trades = 2;</code>
     */
    java.util.List<com.example.protobuf.TradeProto.TradeEvent> 
        getTradesList();
    /**
     * <code>repeated .com.example.TradeEvent trades = 2;</code>
     */
    com.example.protobuf.TradeProto.TradeEvent getTrades(int index);
    /**
     * <code>repeated .com.example.TradeEvent trades = 2;</code>
     */
    int getTradesCount();
    /**
     * <code>repeated .com.example.TradeEvent trades = 2;</code>
     */
    java.util.List<? extends com.example.protobuf.TradeProto.TradeEventOrBuilder> 
        getTradesOrBuilderList();
    /**
     * <code>repeated .com.example.TradeEvent trades = 2;</code>
     */
    com.example.protobuf.TradeProto.TradeEventOrBuilder getTradesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.example.DailyBalanceRequest}
   */
  public static final class DailyBalanceRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.example.DailyBalanceRequest)
      DailyBalanceRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        DailyBalanceRequest.class.getName());
    }
    // Use DailyBalanceRequest.newBuilder() to construct.
    private DailyBalanceRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DailyBalanceRequest() {
      date_ = "";
      trades_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protobuf.BalanceProto.internal_static_com_example_DailyBalanceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protobuf.BalanceProto.internal_static_com_example_DailyBalanceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protobuf.BalanceProto.DailyBalanceRequest.class, com.example.protobuf.BalanceProto.DailyBalanceRequest.Builder.class);
    }

    public static final int DATE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object date_ = "";
    /**
     * <code>string date = 1;</code>
     * @return The date.
     */
    @java.lang.Override
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 1;</code>
     * @return The bytes for date.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRADES_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<com.example.protobuf.TradeProto.TradeEvent> trades_;
    /**
     * <code>repeated .com.example.TradeEvent trades = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.protobuf.TradeProto.TradeEvent> getTradesList() {
      return trades_;
    }
    /**
     * <code>repeated .com.example.TradeEvent trades = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.protobuf.TradeProto.TradeEventOrBuilder> 
        getTradesOrBuilderList() {
      return trades_;
    }
    /**
     * <code>repeated .com.example.TradeEvent trades = 2;</code>
     */
    @java.lang.Override
    public int getTradesCount() {
      return trades_.size();
    }
    /**
     * <code>repeated .com.example.TradeEvent trades = 2;</code>
     */
    @java.lang.Override
    public com.example.protobuf.TradeProto.TradeEvent getTrades(int index) {
      return trades_.get(index);
    }
    /**
     * <code>repeated .com.example.TradeEvent trades = 2;</code>
     */
    @java.lang.Override
    public com.example.protobuf.TradeProto.TradeEventOrBuilder getTradesOrBuilder(
        int index) {
      return trades_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(date_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, date_);
      }
      for (int i = 0; i < trades_.size(); i++) {
        output.writeMessage(2, trades_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(date_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, date_);
      }
      for (int i = 0; i < trades_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, trades_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.protobuf.BalanceProto.DailyBalanceRequest)) {
        return super.equals(obj);
      }
      com.example.protobuf.BalanceProto.DailyBalanceRequest other = (com.example.protobuf.BalanceProto.DailyBalanceRequest) obj;

      if (!getDate()
          .equals(other.getDate())) return false;
      if (!getTradesList()
          .equals(other.getTradesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      if (getTradesCount() > 0) {
        hash = (37 * hash) + TRADES_FIELD_NUMBER;
        hash = (53 * hash) + getTradesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.protobuf.BalanceProto.DailyBalanceRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.BalanceProto.DailyBalanceRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.BalanceProto.DailyBalanceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.BalanceProto.DailyBalanceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.BalanceProto.DailyBalanceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.BalanceProto.DailyBalanceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.BalanceProto.DailyBalanceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.BalanceProto.DailyBalanceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.protobuf.BalanceProto.DailyBalanceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.protobuf.BalanceProto.DailyBalanceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobuf.BalanceProto.DailyBalanceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.BalanceProto.DailyBalanceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.protobuf.BalanceProto.DailyBalanceRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.DailyBalanceRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.DailyBalanceRequest)
        com.example.protobuf.BalanceProto.DailyBalanceRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.protobuf.BalanceProto.internal_static_com_example_DailyBalanceRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.protobuf.BalanceProto.internal_static_com_example_DailyBalanceRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.protobuf.BalanceProto.DailyBalanceRequest.class, com.example.protobuf.BalanceProto.DailyBalanceRequest.Builder.class);
      }

      // Construct using com.example.protobuf.BalanceProto.DailyBalanceRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        date_ = "";
        if (tradesBuilder_ == null) {
          trades_ = java.util.Collections.emptyList();
        } else {
          trades_ = null;
          tradesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.protobuf.BalanceProto.internal_static_com_example_DailyBalanceRequest_descriptor;
      }

      @java.lang.Override
      public com.example.protobuf.BalanceProto.DailyBalanceRequest getDefaultInstanceForType() {
        return com.example.protobuf.BalanceProto.DailyBalanceRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.protobuf.BalanceProto.DailyBalanceRequest build() {
        com.example.protobuf.BalanceProto.DailyBalanceRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.protobuf.BalanceProto.DailyBalanceRequest buildPartial() {
        com.example.protobuf.BalanceProto.DailyBalanceRequest result = new com.example.protobuf.BalanceProto.DailyBalanceRequest(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.example.protobuf.BalanceProto.DailyBalanceRequest result) {
        if (tradesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            trades_ = java.util.Collections.unmodifiableList(trades_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.trades_ = trades_;
        } else {
          result.trades_ = tradesBuilder_.build();
        }
      }

      private void buildPartial0(com.example.protobuf.BalanceProto.DailyBalanceRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.date_ = date_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.protobuf.BalanceProto.DailyBalanceRequest) {
          return mergeFrom((com.example.protobuf.BalanceProto.DailyBalanceRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.protobuf.BalanceProto.DailyBalanceRequest other) {
        if (other == com.example.protobuf.BalanceProto.DailyBalanceRequest.getDefaultInstance()) return this;
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (tradesBuilder_ == null) {
          if (!other.trades_.isEmpty()) {
            if (trades_.isEmpty()) {
              trades_ = other.trades_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTradesIsMutable();
              trades_.addAll(other.trades_);
            }
            onChanged();
          }
        } else {
          if (!other.trades_.isEmpty()) {
            if (tradesBuilder_.isEmpty()) {
              tradesBuilder_.dispose();
              tradesBuilder_ = null;
              trades_ = other.trades_;
              bitField0_ = (bitField0_ & ~0x00000002);
              tradesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetTradesFieldBuilder() : null;
            } else {
              tradesBuilder_.addAllMessages(other.trades_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                date_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                com.example.protobuf.TradeProto.TradeEvent m =
                    input.readMessage(
                        com.example.protobuf.TradeProto.TradeEvent.parser(),
                        extensionRegistry);
                if (tradesBuilder_ == null) {
                  ensureTradesIsMutable();
                  trades_.add(m);
                } else {
                  tradesBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 1;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 1;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 1;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        date_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        date_ = getDefaultInstance().getDate();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string date = 1;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        date_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.util.List<com.example.protobuf.TradeProto.TradeEvent> trades_ =
        java.util.Collections.emptyList();
      private void ensureTradesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          trades_ = new java.util.ArrayList<com.example.protobuf.TradeProto.TradeEvent>(trades_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.protobuf.TradeProto.TradeEvent, com.example.protobuf.TradeProto.TradeEvent.Builder, com.example.protobuf.TradeProto.TradeEventOrBuilder> tradesBuilder_;

      /**
       * <code>repeated .com.example.TradeEvent trades = 2;</code>
       */
      public java.util.List<com.example.protobuf.TradeProto.TradeEvent> getTradesList() {
        if (tradesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(trades_);
        } else {
          return tradesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.example.TradeEvent trades = 2;</code>
       */
      public int getTradesCount() {
        if (tradesBuilder_ == null) {
          return trades_.size();
        } else {
          return tradesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.example.TradeEvent trades = 2;</code>
       */
      public com.example.protobuf.TradeProto.TradeEvent getTrades(int index) {
        if (tradesBuilder_ == null) {
          return trades_.get(index);
        } else {
          return tradesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.example.TradeEvent trades = 2;</code>
       */
      public Builder setTrades(
          int index, com.example.protobuf.TradeProto.TradeEvent value) {
        if (tradesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTradesIsMutable();
          trades_.set(index, value);
          onChanged();
        } else {
          tradesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.TradeEvent trades = 2;</code>
       */
      public Builder setTrades(
          int index, com.example.protobuf.TradeProto.TradeEvent.Builder builderForValue) {
        if (tradesBuilder_ == null) {
          ensureTradesIsMutable();
          trades_.set(index, builderForValue.build());
          onChanged();
        } else {
          tradesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.TradeEvent trades = 2;</code>
       */
      public Builder addTrades(com.example.protobuf.TradeProto.TradeEvent value) {
        if (tradesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTradesIsMutable();
          trades_.add(value);
          onChanged();
        } else {
          tradesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.TradeEvent trades = 2;</code>
       */
      public Builder addTrades(
          int index, com.example.protobuf.TradeProto.TradeEvent value) {
        if (tradesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTradesIsMutable();
          trades_.add(index, value);
          onChanged();
        } else {
          tradesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.TradeEvent trades = 2;</code>
       */
      public Builder addTrades(
          com.example.protobuf.TradeProto.TradeEvent.Builder builderForValue) {
        if (tradesBuilder_ == null) {
          ensureTradesIsMutable();
          trades_.add(builderForValue.build());
          onChanged();
        } else {
          tradesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.TradeEvent trades = 2;</code>
       */
      public Builder addTrades(
          int index, com.example.protobuf.TradeProto.TradeEvent.Builder builderForValue) {
        if (tradesBuilder_ == null) {
          ensureTradesIsMutable();
          trades_.add(index, builderForValue.build());
          onChanged();
        } else {
          tradesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.TradeEvent trades = 2;</code>
       */
      public Builder addAllTrades(
          java.lang.Iterable<? extends com.example.protobuf.TradeProto.TradeEvent> values) {
        if (tradesBuilder_ == null) {
          ensureTradesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, trades_);
          onChanged();
        } else {
          tradesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.TradeEvent trades = 2;</code>
       */
      public Builder clearTrades() {
        if (tradesBuilder_ == null) {
          trades_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          tradesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.example.TradeEvent trades = 2;</code>
       */
      public Builder removeTrades(int index) {
        if (tradesBuilder_ == null) {
          ensureTradesIsMutable();
          trades_.remove(index);
          onChanged();
        } else {
          tradesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.TradeEvent trades = 2;</code>
       */
      public com.example.protobuf.TradeProto.TradeEvent.Builder getTradesBuilder(
          int index) {
        return internalGetTradesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.example.TradeEvent trades = 2;</code>
       */
      public com.example.protobuf.TradeProto.TradeEventOrBuilder getTradesOrBuilder(
          int index) {
        if (tradesBuilder_ == null) {
          return trades_.get(index);  } else {
          return tradesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.example.TradeEvent trades = 2;</code>
       */
      public java.util.List<? extends com.example.protobuf.TradeProto.TradeEventOrBuilder> 
           getTradesOrBuilderList() {
        if (tradesBuilder_ != null) {
          return tradesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(trades_);
        }
      }
      /**
       * <code>repeated .com.example.TradeEvent trades = 2;</code>
       */
      public com.example.protobuf.TradeProto.TradeEvent.Builder addTradesBuilder() {
        return internalGetTradesFieldBuilder().addBuilder(
            com.example.protobuf.TradeProto.TradeEvent.getDefaultInstance());
      }
      /**
       * <code>repeated .com.example.TradeEvent trades = 2;</code>
       */
      public com.example.protobuf.TradeProto.TradeEvent.Builder addTradesBuilder(
          int index) {
        return internalGetTradesFieldBuilder().addBuilder(
            index, com.example.protobuf.TradeProto.TradeEvent.getDefaultInstance());
      }
      /**
       * <code>repeated .com.example.TradeEvent trades = 2;</code>
       */
      public java.util.List<com.example.protobuf.TradeProto.TradeEvent.Builder> 
           getTradesBuilderList() {
        return internalGetTradesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.protobuf.TradeProto.TradeEvent, com.example.protobuf.TradeProto.TradeEvent.Builder, com.example.protobuf.TradeProto.TradeEventOrBuilder> 
          internalGetTradesFieldBuilder() {
        if (tradesBuilder_ == null) {
          tradesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.example.protobuf.TradeProto.TradeEvent, com.example.protobuf.TradeProto.TradeEvent.Builder, com.example.protobuf.TradeProto.TradeEventOrBuilder>(
                  trades_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          trades_ = null;
        }
        return tradesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.example.DailyBalanceRequest)
    }

    // @@protoc_insertion_point(class_scope:com.example.DailyBalanceRequest)
    private static final com.example.protobuf.BalanceProto.DailyBalanceRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.protobuf.BalanceProto.DailyBalanceRequest();
    }

    public static com.example.protobuf.BalanceProto.DailyBalanceRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DailyBalanceRequest>
        PARSER = new com.google.protobuf.AbstractParser<DailyBalanceRequest>() {
      @java.lang.Override
      public DailyBalanceRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DailyBalanceRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DailyBalanceRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.protobuf.BalanceProto.DailyBalanceRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_DailyBalanceRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_DailyBalanceRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025balance-request.proto\022\013com.example\032\013tr" +
      "ade.proto\"L\n\023DailyBalanceRequest\022\014\n\004date" +
      "\030\001 \001(\t\022\'\n\006trades\030\002 \003(\0132\027.com.example.Tra" +
      "deEventB$\n\024com.example.protobufB\014Balance" +
      "Protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.protobuf.TradeProto.getDescriptor(),
        });
    internal_static_com_example_DailyBalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_DailyBalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_DailyBalanceRequest_descriptor,
        new java.lang.String[] { "Date", "Trades", });
    descriptor.resolveAllFeaturesImmutable();
    com.example.protobuf.TradeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
