// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ote.proto
// Protobuf Java Version: 4.32.0

package com.example.protobuf;

@com.google.protobuf.Generated
public final class OTEProto {
  private OTEProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      OTEProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OTEUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.OTEUpdate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string account_id = 1;</code>
     * @return The accountId.
     */
    java.lang.String getAccountId();
    /**
     * <code>string account_id = 1;</code>
     * @return The bytes for accountId.
     */
    com.google.protobuf.ByteString
        getAccountIdBytes();

    /**
     * <code>double ote = 2;</code>
     * @return The ote.
     */
    double getOte();
  }
  /**
   * Protobuf type {@code com.example.OTEUpdate}
   */
  public static final class OTEUpdate extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.example.OTEUpdate)
      OTEUpdateOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        OTEUpdate.class.getName());
    }
    // Use OTEUpdate.newBuilder() to construct.
    private OTEUpdate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private OTEUpdate() {
      accountId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protobuf.OTEProto.internal_static_com_example_OTEUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protobuf.OTEProto.internal_static_com_example_OTEUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protobuf.OTEProto.OTEUpdate.class, com.example.protobuf.OTEProto.OTEUpdate.Builder.class);
    }

    public static final int ACCOUNT_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object accountId_ = "";
    /**
     * <code>string account_id = 1;</code>
     * @return The accountId.
     */
    @java.lang.Override
    public java.lang.String getAccountId() {
      java.lang.Object ref = accountId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountId_ = s;
        return s;
      }
    }
    /**
     * <code>string account_id = 1;</code>
     * @return The bytes for accountId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountIdBytes() {
      java.lang.Object ref = accountId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OTE_FIELD_NUMBER = 2;
    private double ote_ = 0D;
    /**
     * <code>double ote = 2;</code>
     * @return The ote.
     */
    @java.lang.Override
    public double getOte() {
      return ote_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accountId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, accountId_);
      }
      if (java.lang.Double.doubleToRawLongBits(ote_) != 0) {
        output.writeDouble(2, ote_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accountId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, accountId_);
      }
      if (java.lang.Double.doubleToRawLongBits(ote_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, ote_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.protobuf.OTEProto.OTEUpdate)) {
        return super.equals(obj);
      }
      com.example.protobuf.OTEProto.OTEUpdate other = (com.example.protobuf.OTEProto.OTEUpdate) obj;

      if (!getAccountId()
          .equals(other.getAccountId())) return false;
      if (java.lang.Double.doubleToLongBits(getOte())
          != java.lang.Double.doubleToLongBits(
              other.getOte())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCOUNT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAccountId().hashCode();
      hash = (37 * hash) + OTE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getOte()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.protobuf.OTEProto.OTEUpdate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.OTEProto.OTEUpdate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.OTEProto.OTEUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.OTEProto.OTEUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.OTEProto.OTEUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.OTEProto.OTEUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.OTEProto.OTEUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.OTEProto.OTEUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.protobuf.OTEProto.OTEUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.protobuf.OTEProto.OTEUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobuf.OTEProto.OTEUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.OTEProto.OTEUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.protobuf.OTEProto.OTEUpdate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.OTEUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.OTEUpdate)
        com.example.protobuf.OTEProto.OTEUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.protobuf.OTEProto.internal_static_com_example_OTEUpdate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.protobuf.OTEProto.internal_static_com_example_OTEUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.protobuf.OTEProto.OTEUpdate.class, com.example.protobuf.OTEProto.OTEUpdate.Builder.class);
      }

      // Construct using com.example.protobuf.OTEProto.OTEUpdate.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        accountId_ = "";
        ote_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.protobuf.OTEProto.internal_static_com_example_OTEUpdate_descriptor;
      }

      @java.lang.Override
      public com.example.protobuf.OTEProto.OTEUpdate getDefaultInstanceForType() {
        return com.example.protobuf.OTEProto.OTEUpdate.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.protobuf.OTEProto.OTEUpdate build() {
        com.example.protobuf.OTEProto.OTEUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.protobuf.OTEProto.OTEUpdate buildPartial() {
        com.example.protobuf.OTEProto.OTEUpdate result = new com.example.protobuf.OTEProto.OTEUpdate(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.protobuf.OTEProto.OTEUpdate result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.accountId_ = accountId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.ote_ = ote_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.protobuf.OTEProto.OTEUpdate) {
          return mergeFrom((com.example.protobuf.OTEProto.OTEUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.protobuf.OTEProto.OTEUpdate other) {
        if (other == com.example.protobuf.OTEProto.OTEUpdate.getDefaultInstance()) return this;
        if (!other.getAccountId().isEmpty()) {
          accountId_ = other.accountId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (java.lang.Double.doubleToRawLongBits(other.getOte()) != 0) {
          setOte(other.getOte());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                accountId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 17: {
                ote_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object accountId_ = "";
      /**
       * <code>string account_id = 1;</code>
       * @return The accountId.
       */
      public java.lang.String getAccountId() {
        java.lang.Object ref = accountId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accountId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string account_id = 1;</code>
       * @return The bytes for accountId.
       */
      public com.google.protobuf.ByteString
          getAccountIdBytes() {
        java.lang.Object ref = accountId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string account_id = 1;</code>
       * @param value The accountId to set.
       * @return This builder for chaining.
       */
      public Builder setAccountId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        accountId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string account_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountId() {
        accountId_ = getDefaultInstance().getAccountId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string account_id = 1;</code>
       * @param value The bytes for accountId to set.
       * @return This builder for chaining.
       */
      public Builder setAccountIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        accountId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private double ote_ ;
      /**
       * <code>double ote = 2;</code>
       * @return The ote.
       */
      @java.lang.Override
      public double getOte() {
        return ote_;
      }
      /**
       * <code>double ote = 2;</code>
       * @param value The ote to set.
       * @return This builder for chaining.
       */
      public Builder setOte(double value) {

        ote_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double ote = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOte() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ote_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.OTEUpdate)
    }

    // @@protoc_insertion_point(class_scope:com.example.OTEUpdate)
    private static final com.example.protobuf.OTEProto.OTEUpdate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.protobuf.OTEProto.OTEUpdate();
    }

    public static com.example.protobuf.OTEProto.OTEUpdate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OTEUpdate>
        PARSER = new com.google.protobuf.AbstractParser<OTEUpdate>() {
      @java.lang.Override
      public OTEUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OTEUpdate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OTEUpdate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.protobuf.OTEProto.OTEUpdate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OTEUpdateResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.OTEUpdateResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string date = 1;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>string date = 1;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
     */
    java.util.List<com.example.protobuf.OTEProto.OTEUpdate> 
        getAccountOteList();
    /**
     * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
     */
    com.example.protobuf.OTEProto.OTEUpdate getAccountOte(int index);
    /**
     * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
     */
    int getAccountOteCount();
    /**
     * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
     */
    java.util.List<? extends com.example.protobuf.OTEProto.OTEUpdateOrBuilder> 
        getAccountOteOrBuilderList();
    /**
     * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
     */
    com.example.protobuf.OTEProto.OTEUpdateOrBuilder getAccountOteOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.example.OTEUpdateResponse}
   */
  public static final class OTEUpdateResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.example.OTEUpdateResponse)
      OTEUpdateResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        OTEUpdateResponse.class.getName());
    }
    // Use OTEUpdateResponse.newBuilder() to construct.
    private OTEUpdateResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private OTEUpdateResponse() {
      date_ = "";
      accountOte_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protobuf.OTEProto.internal_static_com_example_OTEUpdateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protobuf.OTEProto.internal_static_com_example_OTEUpdateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protobuf.OTEProto.OTEUpdateResponse.class, com.example.protobuf.OTEProto.OTEUpdateResponse.Builder.class);
    }

    public static final int DATE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object date_ = "";
    /**
     * <code>string date = 1;</code>
     * @return The date.
     */
    @java.lang.Override
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 1;</code>
     * @return The bytes for date.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNT_OTE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<com.example.protobuf.OTEProto.OTEUpdate> accountOte_;
    /**
     * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.protobuf.OTEProto.OTEUpdate> getAccountOteList() {
      return accountOte_;
    }
    /**
     * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.protobuf.OTEProto.OTEUpdateOrBuilder> 
        getAccountOteOrBuilderList() {
      return accountOte_;
    }
    /**
     * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
     */
    @java.lang.Override
    public int getAccountOteCount() {
      return accountOte_.size();
    }
    /**
     * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
     */
    @java.lang.Override
    public com.example.protobuf.OTEProto.OTEUpdate getAccountOte(int index) {
      return accountOte_.get(index);
    }
    /**
     * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
     */
    @java.lang.Override
    public com.example.protobuf.OTEProto.OTEUpdateOrBuilder getAccountOteOrBuilder(
        int index) {
      return accountOte_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(date_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, date_);
      }
      for (int i = 0; i < accountOte_.size(); i++) {
        output.writeMessage(2, accountOte_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(date_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, date_);
      }
      for (int i = 0; i < accountOte_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, accountOte_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.protobuf.OTEProto.OTEUpdateResponse)) {
        return super.equals(obj);
      }
      com.example.protobuf.OTEProto.OTEUpdateResponse other = (com.example.protobuf.OTEProto.OTEUpdateResponse) obj;

      if (!getDate()
          .equals(other.getDate())) return false;
      if (!getAccountOteList()
          .equals(other.getAccountOteList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      if (getAccountOteCount() > 0) {
        hash = (37 * hash) + ACCOUNT_OTE_FIELD_NUMBER;
        hash = (53 * hash) + getAccountOteList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.protobuf.OTEProto.OTEUpdateResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.OTEProto.OTEUpdateResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.OTEProto.OTEUpdateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.OTEProto.OTEUpdateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.OTEProto.OTEUpdateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.OTEProto.OTEUpdateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.OTEProto.OTEUpdateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.OTEProto.OTEUpdateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.protobuf.OTEProto.OTEUpdateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.protobuf.OTEProto.OTEUpdateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobuf.OTEProto.OTEUpdateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.OTEProto.OTEUpdateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.protobuf.OTEProto.OTEUpdateResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.OTEUpdateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.OTEUpdateResponse)
        com.example.protobuf.OTEProto.OTEUpdateResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.protobuf.OTEProto.internal_static_com_example_OTEUpdateResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.protobuf.OTEProto.internal_static_com_example_OTEUpdateResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.protobuf.OTEProto.OTEUpdateResponse.class, com.example.protobuf.OTEProto.OTEUpdateResponse.Builder.class);
      }

      // Construct using com.example.protobuf.OTEProto.OTEUpdateResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        date_ = "";
        if (accountOteBuilder_ == null) {
          accountOte_ = java.util.Collections.emptyList();
        } else {
          accountOte_ = null;
          accountOteBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.protobuf.OTEProto.internal_static_com_example_OTEUpdateResponse_descriptor;
      }

      @java.lang.Override
      public com.example.protobuf.OTEProto.OTEUpdateResponse getDefaultInstanceForType() {
        return com.example.protobuf.OTEProto.OTEUpdateResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.protobuf.OTEProto.OTEUpdateResponse build() {
        com.example.protobuf.OTEProto.OTEUpdateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.protobuf.OTEProto.OTEUpdateResponse buildPartial() {
        com.example.protobuf.OTEProto.OTEUpdateResponse result = new com.example.protobuf.OTEProto.OTEUpdateResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.example.protobuf.OTEProto.OTEUpdateResponse result) {
        if (accountOteBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            accountOte_ = java.util.Collections.unmodifiableList(accountOte_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.accountOte_ = accountOte_;
        } else {
          result.accountOte_ = accountOteBuilder_.build();
        }
      }

      private void buildPartial0(com.example.protobuf.OTEProto.OTEUpdateResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.date_ = date_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.protobuf.OTEProto.OTEUpdateResponse) {
          return mergeFrom((com.example.protobuf.OTEProto.OTEUpdateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.protobuf.OTEProto.OTEUpdateResponse other) {
        if (other == com.example.protobuf.OTEProto.OTEUpdateResponse.getDefaultInstance()) return this;
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (accountOteBuilder_ == null) {
          if (!other.accountOte_.isEmpty()) {
            if (accountOte_.isEmpty()) {
              accountOte_ = other.accountOte_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAccountOteIsMutable();
              accountOte_.addAll(other.accountOte_);
            }
            onChanged();
          }
        } else {
          if (!other.accountOte_.isEmpty()) {
            if (accountOteBuilder_.isEmpty()) {
              accountOteBuilder_.dispose();
              accountOteBuilder_ = null;
              accountOte_ = other.accountOte_;
              bitField0_ = (bitField0_ & ~0x00000002);
              accountOteBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetAccountOteFieldBuilder() : null;
            } else {
              accountOteBuilder_.addAllMessages(other.accountOte_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                date_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                com.example.protobuf.OTEProto.OTEUpdate m =
                    input.readMessage(
                        com.example.protobuf.OTEProto.OTEUpdate.parser(),
                        extensionRegistry);
                if (accountOteBuilder_ == null) {
                  ensureAccountOteIsMutable();
                  accountOte_.add(m);
                } else {
                  accountOteBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 1;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 1;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 1;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        date_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        date_ = getDefaultInstance().getDate();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string date = 1;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        date_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.util.List<com.example.protobuf.OTEProto.OTEUpdate> accountOte_ =
        java.util.Collections.emptyList();
      private void ensureAccountOteIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          accountOte_ = new java.util.ArrayList<com.example.protobuf.OTEProto.OTEUpdate>(accountOte_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.protobuf.OTEProto.OTEUpdate, com.example.protobuf.OTEProto.OTEUpdate.Builder, com.example.protobuf.OTEProto.OTEUpdateOrBuilder> accountOteBuilder_;

      /**
       * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
       */
      public java.util.List<com.example.protobuf.OTEProto.OTEUpdate> getAccountOteList() {
        if (accountOteBuilder_ == null) {
          return java.util.Collections.unmodifiableList(accountOte_);
        } else {
          return accountOteBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
       */
      public int getAccountOteCount() {
        if (accountOteBuilder_ == null) {
          return accountOte_.size();
        } else {
          return accountOteBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
       */
      public com.example.protobuf.OTEProto.OTEUpdate getAccountOte(int index) {
        if (accountOteBuilder_ == null) {
          return accountOte_.get(index);
        } else {
          return accountOteBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
       */
      public Builder setAccountOte(
          int index, com.example.protobuf.OTEProto.OTEUpdate value) {
        if (accountOteBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountOteIsMutable();
          accountOte_.set(index, value);
          onChanged();
        } else {
          accountOteBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
       */
      public Builder setAccountOte(
          int index, com.example.protobuf.OTEProto.OTEUpdate.Builder builderForValue) {
        if (accountOteBuilder_ == null) {
          ensureAccountOteIsMutable();
          accountOte_.set(index, builderForValue.build());
          onChanged();
        } else {
          accountOteBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
       */
      public Builder addAccountOte(com.example.protobuf.OTEProto.OTEUpdate value) {
        if (accountOteBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountOteIsMutable();
          accountOte_.add(value);
          onChanged();
        } else {
          accountOteBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
       */
      public Builder addAccountOte(
          int index, com.example.protobuf.OTEProto.OTEUpdate value) {
        if (accountOteBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountOteIsMutable();
          accountOte_.add(index, value);
          onChanged();
        } else {
          accountOteBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
       */
      public Builder addAccountOte(
          com.example.protobuf.OTEProto.OTEUpdate.Builder builderForValue) {
        if (accountOteBuilder_ == null) {
          ensureAccountOteIsMutable();
          accountOte_.add(builderForValue.build());
          onChanged();
        } else {
          accountOteBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
       */
      public Builder addAccountOte(
          int index, com.example.protobuf.OTEProto.OTEUpdate.Builder builderForValue) {
        if (accountOteBuilder_ == null) {
          ensureAccountOteIsMutable();
          accountOte_.add(index, builderForValue.build());
          onChanged();
        } else {
          accountOteBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
       */
      public Builder addAllAccountOte(
          java.lang.Iterable<? extends com.example.protobuf.OTEProto.OTEUpdate> values) {
        if (accountOteBuilder_ == null) {
          ensureAccountOteIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, accountOte_);
          onChanged();
        } else {
          accountOteBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
       */
      public Builder clearAccountOte() {
        if (accountOteBuilder_ == null) {
          accountOte_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          accountOteBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
       */
      public Builder removeAccountOte(int index) {
        if (accountOteBuilder_ == null) {
          ensureAccountOteIsMutable();
          accountOte_.remove(index);
          onChanged();
        } else {
          accountOteBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
       */
      public com.example.protobuf.OTEProto.OTEUpdate.Builder getAccountOteBuilder(
          int index) {
        return internalGetAccountOteFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
       */
      public com.example.protobuf.OTEProto.OTEUpdateOrBuilder getAccountOteOrBuilder(
          int index) {
        if (accountOteBuilder_ == null) {
          return accountOte_.get(index);  } else {
          return accountOteBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
       */
      public java.util.List<? extends com.example.protobuf.OTEProto.OTEUpdateOrBuilder> 
           getAccountOteOrBuilderList() {
        if (accountOteBuilder_ != null) {
          return accountOteBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(accountOte_);
        }
      }
      /**
       * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
       */
      public com.example.protobuf.OTEProto.OTEUpdate.Builder addAccountOteBuilder() {
        return internalGetAccountOteFieldBuilder().addBuilder(
            com.example.protobuf.OTEProto.OTEUpdate.getDefaultInstance());
      }
      /**
       * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
       */
      public com.example.protobuf.OTEProto.OTEUpdate.Builder addAccountOteBuilder(
          int index) {
        return internalGetAccountOteFieldBuilder().addBuilder(
            index, com.example.protobuf.OTEProto.OTEUpdate.getDefaultInstance());
      }
      /**
       * <code>repeated .com.example.OTEUpdate account_ote = 2;</code>
       */
      public java.util.List<com.example.protobuf.OTEProto.OTEUpdate.Builder> 
           getAccountOteBuilderList() {
        return internalGetAccountOteFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.protobuf.OTEProto.OTEUpdate, com.example.protobuf.OTEProto.OTEUpdate.Builder, com.example.protobuf.OTEProto.OTEUpdateOrBuilder> 
          internalGetAccountOteFieldBuilder() {
        if (accountOteBuilder_ == null) {
          accountOteBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.example.protobuf.OTEProto.OTEUpdate, com.example.protobuf.OTEProto.OTEUpdate.Builder, com.example.protobuf.OTEProto.OTEUpdateOrBuilder>(
                  accountOte_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          accountOte_ = null;
        }
        return accountOteBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.example.OTEUpdateResponse)
    }

    // @@protoc_insertion_point(class_scope:com.example.OTEUpdateResponse)
    private static final com.example.protobuf.OTEProto.OTEUpdateResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.protobuf.OTEProto.OTEUpdateResponse();
    }

    public static com.example.protobuf.OTEProto.OTEUpdateResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OTEUpdateResponse>
        PARSER = new com.google.protobuf.AbstractParser<OTEUpdateResponse>() {
      @java.lang.Override
      public OTEUpdateResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OTEUpdateResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OTEUpdateResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.protobuf.OTEProto.OTEUpdateResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_OTEUpdate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_OTEUpdate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_OTEUpdateResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_OTEUpdateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tote.proto\022\013com.example\",\n\tOTEUpdate\022\022\n" +
      "\naccount_id\030\001 \001(\t\022\013\n\003ote\030\002 \001(\001\"N\n\021OTEUpd" +
      "ateResponse\022\014\n\004date\030\001 \001(\t\022+\n\013account_ote" +
      "\030\002 \003(\0132\026.com.example.OTEUpdateB \n\024com.ex" +
      "ample.protobufB\010OTEProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_OTEUpdate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_OTEUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_OTEUpdate_descriptor,
        new java.lang.String[] { "AccountId", "Ote", });
    internal_static_com_example_OTEUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_OTEUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_OTEUpdateResponse_descriptor,
        new java.lang.String[] { "Date", "AccountOte", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
