// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trade.proto
// Protobuf Java Version: 4.32.0

package com.example.protobuf;

@com.google.protobuf.Generated
public final class TradeProto {
  private TradeProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      TradeProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.example.Direction}
   */
  public enum Direction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BUY = 0;</code>
     */
    BUY(0),
    /**
     * <code>SELL = 1;</code>
     */
    SELL(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        Direction.class.getName());
    }
    /**
     * <code>BUY = 0;</code>
     */
    public static final int BUY_VALUE = 0;
    /**
     * <code>SELL = 1;</code>
     */
    public static final int SELL_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Direction valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Direction forNumber(int value) {
      switch (value) {
        case 0: return BUY;
        case 1: return SELL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Direction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Direction> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Direction>() {
            public Direction findValueByNumber(int number) {
              return Direction.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.example.protobuf.TradeProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Direction[] VALUES = values();

    public static Direction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Direction(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.example.Direction)
  }

  public interface TradeEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.TradeEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string trade_id = 1;</code>
     * @return The tradeId.
     */
    java.lang.String getTradeId();
    /**
     * <code>string trade_id = 1;</code>
     * @return The bytes for tradeId.
     */
    com.google.protobuf.ByteString
        getTradeIdBytes();

    /**
     * <code>string account_id = 2;</code>
     * @return The accountId.
     */
    java.lang.String getAccountId();
    /**
     * <code>string account_id = 2;</code>
     * @return The bytes for accountId.
     */
    com.google.protobuf.ByteString
        getAccountIdBytes();

    /**
     * <code>string instrument_id = 3;</code>
     * @return The instrumentId.
     */
    java.lang.String getInstrumentId();
    /**
     * <code>string instrument_id = 3;</code>
     * @return The bytes for instrumentId.
     */
    com.google.protobuf.ByteString
        getInstrumentIdBytes();

    /**
     * <code>.com.example.Direction direction = 4;</code>
     * @return The enum numeric value on the wire for direction.
     */
    int getDirectionValue();
    /**
     * <code>.com.example.Direction direction = 4;</code>
     * @return The direction.
     */
    com.example.protobuf.TradeProto.Direction getDirection();

    /**
     * <code>int32 quantity = 5;</code>
     * @return The quantity.
     */
    int getQuantity();

    /**
     * <code>double price = 6;</code>
     * @return The price.
     */
    double getPrice();

    /**
     * <code>string unit = 7;</code>
     * @return The unit.
     */
    java.lang.String getUnit();
    /**
     * <code>string unit = 7;</code>
     * @return The bytes for unit.
     */
    com.google.protobuf.ByteString
        getUnitBytes();

    /**
     * <code>string delivery_type = 8;</code>
     * @return The deliveryType.
     */
    java.lang.String getDeliveryType();
    /**
     * <code>string delivery_type = 8;</code>
     * @return The bytes for deliveryType.
     */
    com.google.protobuf.ByteString
        getDeliveryTypeBytes();

    /**
     * <code>string status = 9;</code>
     * @return The status.
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 9;</code>
     * @return The bytes for status.
     */
    com.google.protobuf.ByteString
        getStatusBytes();
  }
  /**
   * Protobuf type {@code com.example.TradeEvent}
   */
  public static final class TradeEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.example.TradeEvent)
      TradeEventOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        TradeEvent.class.getName());
    }
    // Use TradeEvent.newBuilder() to construct.
    private TradeEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TradeEvent() {
      tradeId_ = "";
      accountId_ = "";
      instrumentId_ = "";
      direction_ = 0;
      unit_ = "";
      deliveryType_ = "";
      status_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protobuf.TradeProto.internal_static_com_example_TradeEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protobuf.TradeProto.internal_static_com_example_TradeEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protobuf.TradeProto.TradeEvent.class, com.example.protobuf.TradeProto.TradeEvent.Builder.class);
    }

    public static final int TRADE_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object tradeId_ = "";
    /**
     * <code>string trade_id = 1;</code>
     * @return The tradeId.
     */
    @java.lang.Override
    public java.lang.String getTradeId() {
      java.lang.Object ref = tradeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tradeId_ = s;
        return s;
      }
    }
    /**
     * <code>string trade_id = 1;</code>
     * @return The bytes for tradeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTradeIdBytes() {
      java.lang.Object ref = tradeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tradeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNT_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object accountId_ = "";
    /**
     * <code>string account_id = 2;</code>
     * @return The accountId.
     */
    @java.lang.Override
    public java.lang.String getAccountId() {
      java.lang.Object ref = accountId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountId_ = s;
        return s;
      }
    }
    /**
     * <code>string account_id = 2;</code>
     * @return The bytes for accountId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountIdBytes() {
      java.lang.Object ref = accountId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INSTRUMENT_ID_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object instrumentId_ = "";
    /**
     * <code>string instrument_id = 3;</code>
     * @return The instrumentId.
     */
    @java.lang.Override
    public java.lang.String getInstrumentId() {
      java.lang.Object ref = instrumentId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instrumentId_ = s;
        return s;
      }
    }
    /**
     * <code>string instrument_id = 3;</code>
     * @return The bytes for instrumentId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInstrumentIdBytes() {
      java.lang.Object ref = instrumentId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instrumentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRECTION_FIELD_NUMBER = 4;
    private int direction_ = 0;
    /**
     * <code>.com.example.Direction direction = 4;</code>
     * @return The enum numeric value on the wire for direction.
     */
    @java.lang.Override public int getDirectionValue() {
      return direction_;
    }
    /**
     * <code>.com.example.Direction direction = 4;</code>
     * @return The direction.
     */
    @java.lang.Override public com.example.protobuf.TradeProto.Direction getDirection() {
      com.example.protobuf.TradeProto.Direction result = com.example.protobuf.TradeProto.Direction.forNumber(direction_);
      return result == null ? com.example.protobuf.TradeProto.Direction.UNRECOGNIZED : result;
    }

    public static final int QUANTITY_FIELD_NUMBER = 5;
    private int quantity_ = 0;
    /**
     * <code>int32 quantity = 5;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity_;
    }

    public static final int PRICE_FIELD_NUMBER = 6;
    private double price_ = 0D;
    /**
     * <code>double price = 6;</code>
     * @return The price.
     */
    @java.lang.Override
    public double getPrice() {
      return price_;
    }

    public static final int UNIT_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object unit_ = "";
    /**
     * <code>string unit = 7;</code>
     * @return The unit.
     */
    @java.lang.Override
    public java.lang.String getUnit() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unit_ = s;
        return s;
      }
    }
    /**
     * <code>string unit = 7;</code>
     * @return The bytes for unit.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUnitBytes() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DELIVERY_TYPE_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object deliveryType_ = "";
    /**
     * <code>string delivery_type = 8;</code>
     * @return The deliveryType.
     */
    @java.lang.Override
    public java.lang.String getDeliveryType() {
      java.lang.Object ref = deliveryType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deliveryType_ = s;
        return s;
      }
    }
    /**
     * <code>string delivery_type = 8;</code>
     * @return The bytes for deliveryType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeliveryTypeBytes() {
      java.lang.Object ref = deliveryType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deliveryType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile java.lang.Object status_ = "";
    /**
     * <code>string status = 9;</code>
     * @return The status.
     */
    @java.lang.Override
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string status = 9;</code>
     * @return The bytes for status.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tradeId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, tradeId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accountId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, accountId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(instrumentId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, instrumentId_);
      }
      if (direction_ != com.example.protobuf.TradeProto.Direction.BUY.getNumber()) {
        output.writeEnum(4, direction_);
      }
      if (quantity_ != 0) {
        output.writeInt32(5, quantity_);
      }
      if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
        output.writeDouble(6, price_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unit_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, unit_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deliveryType_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, deliveryType_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 9, status_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tradeId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, tradeId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accountId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, accountId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(instrumentId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, instrumentId_);
      }
      if (direction_ != com.example.protobuf.TradeProto.Direction.BUY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, direction_);
      }
      if (quantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, quantity_);
      }
      if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, price_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unit_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, unit_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deliveryType_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, deliveryType_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(9, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.protobuf.TradeProto.TradeEvent)) {
        return super.equals(obj);
      }
      com.example.protobuf.TradeProto.TradeEvent other = (com.example.protobuf.TradeProto.TradeEvent) obj;

      if (!getTradeId()
          .equals(other.getTradeId())) return false;
      if (!getAccountId()
          .equals(other.getAccountId())) return false;
      if (!getInstrumentId()
          .equals(other.getInstrumentId())) return false;
      if (direction_ != other.direction_) return false;
      if (getQuantity()
          != other.getQuantity()) return false;
      if (java.lang.Double.doubleToLongBits(getPrice())
          != java.lang.Double.doubleToLongBits(
              other.getPrice())) return false;
      if (!getUnit()
          .equals(other.getUnit())) return false;
      if (!getDeliveryType()
          .equals(other.getDeliveryType())) return false;
      if (!getStatus()
          .equals(other.getStatus())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TRADE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTradeId().hashCode();
      hash = (37 * hash) + ACCOUNT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAccountId().hashCode();
      hash = (37 * hash) + INSTRUMENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getInstrumentId().hashCode();
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + direction_;
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrice()));
      hash = (37 * hash) + UNIT_FIELD_NUMBER;
      hash = (53 * hash) + getUnit().hashCode();
      hash = (37 * hash) + DELIVERY_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDeliveryType().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.protobuf.TradeProto.TradeEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.TradeProto.TradeEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.TradeProto.TradeEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.TradeProto.TradeEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.TradeProto.TradeEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.TradeProto.TradeEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.TradeProto.TradeEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.TradeProto.TradeEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.protobuf.TradeProto.TradeEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.protobuf.TradeProto.TradeEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobuf.TradeProto.TradeEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.TradeProto.TradeEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.protobuf.TradeProto.TradeEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.TradeEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.TradeEvent)
        com.example.protobuf.TradeProto.TradeEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.protobuf.TradeProto.internal_static_com_example_TradeEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.protobuf.TradeProto.internal_static_com_example_TradeEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.protobuf.TradeProto.TradeEvent.class, com.example.protobuf.TradeProto.TradeEvent.Builder.class);
      }

      // Construct using com.example.protobuf.TradeProto.TradeEvent.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        tradeId_ = "";
        accountId_ = "";
        instrumentId_ = "";
        direction_ = 0;
        quantity_ = 0;
        price_ = 0D;
        unit_ = "";
        deliveryType_ = "";
        status_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.protobuf.TradeProto.internal_static_com_example_TradeEvent_descriptor;
      }

      @java.lang.Override
      public com.example.protobuf.TradeProto.TradeEvent getDefaultInstanceForType() {
        return com.example.protobuf.TradeProto.TradeEvent.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.protobuf.TradeProto.TradeEvent build() {
        com.example.protobuf.TradeProto.TradeEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.protobuf.TradeProto.TradeEvent buildPartial() {
        com.example.protobuf.TradeProto.TradeEvent result = new com.example.protobuf.TradeProto.TradeEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.protobuf.TradeProto.TradeEvent result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.tradeId_ = tradeId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.accountId_ = accountId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.instrumentId_ = instrumentId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.direction_ = direction_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.quantity_ = quantity_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.price_ = price_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.unit_ = unit_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.deliveryType_ = deliveryType_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.status_ = status_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.protobuf.TradeProto.TradeEvent) {
          return mergeFrom((com.example.protobuf.TradeProto.TradeEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.protobuf.TradeProto.TradeEvent other) {
        if (other == com.example.protobuf.TradeProto.TradeEvent.getDefaultInstance()) return this;
        if (!other.getTradeId().isEmpty()) {
          tradeId_ = other.tradeId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getAccountId().isEmpty()) {
          accountId_ = other.accountId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getInstrumentId().isEmpty()) {
          instrumentId_ = other.instrumentId_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.direction_ != 0) {
          setDirectionValue(other.getDirectionValue());
        }
        if (other.getQuantity() != 0) {
          setQuantity(other.getQuantity());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getPrice()) != 0) {
          setPrice(other.getPrice());
        }
        if (!other.getUnit().isEmpty()) {
          unit_ = other.unit_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (!other.getDeliveryType().isEmpty()) {
          deliveryType_ = other.deliveryType_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                tradeId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                accountId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                instrumentId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                direction_ = input.readEnum();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                quantity_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 49: {
                price_ = input.readDouble();
                bitField0_ |= 0x00000020;
                break;
              } // case 49
              case 58: {
                unit_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                deliveryType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                status_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object tradeId_ = "";
      /**
       * <code>string trade_id = 1;</code>
       * @return The tradeId.
       */
      public java.lang.String getTradeId() {
        java.lang.Object ref = tradeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tradeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string trade_id = 1;</code>
       * @return The bytes for tradeId.
       */
      public com.google.protobuf.ByteString
          getTradeIdBytes() {
        java.lang.Object ref = tradeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tradeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string trade_id = 1;</code>
       * @param value The tradeId to set.
       * @return This builder for chaining.
       */
      public Builder setTradeId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        tradeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string trade_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTradeId() {
        tradeId_ = getDefaultInstance().getTradeId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string trade_id = 1;</code>
       * @param value The bytes for tradeId to set.
       * @return This builder for chaining.
       */
      public Builder setTradeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        tradeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object accountId_ = "";
      /**
       * <code>string account_id = 2;</code>
       * @return The accountId.
       */
      public java.lang.String getAccountId() {
        java.lang.Object ref = accountId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accountId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string account_id = 2;</code>
       * @return The bytes for accountId.
       */
      public com.google.protobuf.ByteString
          getAccountIdBytes() {
        java.lang.Object ref = accountId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string account_id = 2;</code>
       * @param value The accountId to set.
       * @return This builder for chaining.
       */
      public Builder setAccountId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        accountId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string account_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountId() {
        accountId_ = getDefaultInstance().getAccountId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string account_id = 2;</code>
       * @param value The bytes for accountId to set.
       * @return This builder for chaining.
       */
      public Builder setAccountIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        accountId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object instrumentId_ = "";
      /**
       * <code>string instrument_id = 3;</code>
       * @return The instrumentId.
       */
      public java.lang.String getInstrumentId() {
        java.lang.Object ref = instrumentId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          instrumentId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string instrument_id = 3;</code>
       * @return The bytes for instrumentId.
       */
      public com.google.protobuf.ByteString
          getInstrumentIdBytes() {
        java.lang.Object ref = instrumentId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instrumentId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string instrument_id = 3;</code>
       * @param value The instrumentId to set.
       * @return This builder for chaining.
       */
      public Builder setInstrumentId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        instrumentId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string instrument_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstrumentId() {
        instrumentId_ = getDefaultInstance().getInstrumentId();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string instrument_id = 3;</code>
       * @param value The bytes for instrumentId to set.
       * @return This builder for chaining.
       */
      public Builder setInstrumentIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        instrumentId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int direction_ = 0;
      /**
       * <code>.com.example.Direction direction = 4;</code>
       * @return The enum numeric value on the wire for direction.
       */
      @java.lang.Override public int getDirectionValue() {
        return direction_;
      }
      /**
       * <code>.com.example.Direction direction = 4;</code>
       * @param value The enum numeric value on the wire for direction to set.
       * @return This builder for chaining.
       */
      public Builder setDirectionValue(int value) {
        direction_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.com.example.Direction direction = 4;</code>
       * @return The direction.
       */
      @java.lang.Override
      public com.example.protobuf.TradeProto.Direction getDirection() {
        com.example.protobuf.TradeProto.Direction result = com.example.protobuf.TradeProto.Direction.forNumber(direction_);
        return result == null ? com.example.protobuf.TradeProto.Direction.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.example.Direction direction = 4;</code>
       * @param value The direction to set.
       * @return This builder for chaining.
       */
      public Builder setDirection(com.example.protobuf.TradeProto.Direction value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000008;
        direction_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.example.Direction direction = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDirection() {
        bitField0_ = (bitField0_ & ~0x00000008);
        direction_ = 0;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>int32 quantity = 5;</code>
       * @return The quantity.
       */
      @java.lang.Override
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>int32 quantity = 5;</code>
       * @param value The quantity to set.
       * @return This builder for chaining.
       */
      public Builder setQuantity(int value) {

        quantity_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quantity = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000010);
        quantity_ = 0;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>double price = 6;</code>
       * @return The price.
       */
      @java.lang.Override
      public double getPrice() {
        return price_;
      }
      /**
       * <code>double price = 6;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(double value) {

        price_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>double price = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000020);
        price_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object unit_ = "";
      /**
       * <code>string unit = 7;</code>
       * @return The unit.
       */
      public java.lang.String getUnit() {
        java.lang.Object ref = unit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          unit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string unit = 7;</code>
       * @return The bytes for unit.
       */
      public com.google.protobuf.ByteString
          getUnitBytes() {
        java.lang.Object ref = unit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string unit = 7;</code>
       * @param value The unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnit(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        unit_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string unit = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnit() {
        unit_ = getDefaultInstance().getUnit();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string unit = 7;</code>
       * @param value The bytes for unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        unit_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private java.lang.Object deliveryType_ = "";
      /**
       * <code>string delivery_type = 8;</code>
       * @return The deliveryType.
       */
      public java.lang.String getDeliveryType() {
        java.lang.Object ref = deliveryType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deliveryType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string delivery_type = 8;</code>
       * @return The bytes for deliveryType.
       */
      public com.google.protobuf.ByteString
          getDeliveryTypeBytes() {
        java.lang.Object ref = deliveryType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deliveryType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string delivery_type = 8;</code>
       * @param value The deliveryType to set.
       * @return This builder for chaining.
       */
      public Builder setDeliveryType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        deliveryType_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string delivery_type = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeliveryType() {
        deliveryType_ = getDefaultInstance().getDeliveryType();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string delivery_type = 8;</code>
       * @param value The bytes for deliveryType to set.
       * @return This builder for chaining.
       */
      public Builder setDeliveryTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        deliveryType_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string status = 9;</code>
       * @return The status.
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status = 9;</code>
       * @return The bytes for status.
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status = 9;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        status_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>string status = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        status_ = getDefaultInstance().getStatus();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>string status = 9;</code>
       * @param value The bytes for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        status_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.TradeEvent)
    }

    // @@protoc_insertion_point(class_scope:com.example.TradeEvent)
    private static final com.example.protobuf.TradeProto.TradeEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.protobuf.TradeProto.TradeEvent();
    }

    public static com.example.protobuf.TradeProto.TradeEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TradeEvent>
        PARSER = new com.google.protobuf.AbstractParser<TradeEvent>() {
      @java.lang.Override
      public TradeEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TradeEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TradeEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.protobuf.TradeProto.TradeEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_TradeEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_TradeEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013trade.proto\022\013com.example\"\312\001\n\nTradeEven" +
      "t\022\020\n\010trade_id\030\001 \001(\t\022\022\n\naccount_id\030\002 \001(\t\022" +
      "\025\n\rinstrument_id\030\003 \001(\t\022)\n\tdirection\030\004 \001(" +
      "\0162\026.com.example.Direction\022\020\n\010quantity\030\005 " +
      "\001(\005\022\r\n\005price\030\006 \001(\001\022\014\n\004unit\030\007 \001(\t\022\025\n\rdeli" +
      "very_type\030\010 \001(\t\022\016\n\006status\030\t \001(\t*\036\n\tDirec" +
      "tion\022\007\n\003BUY\020\000\022\010\n\004SELL\020\001B\"\n\024com.example.p" +
      "rotobufB\nTradeProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_TradeEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_TradeEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_TradeEvent_descriptor,
        new java.lang.String[] { "TradeId", "AccountId", "InstrumentId", "Direction", "Quantity", "Price", "Unit", "DeliveryType", "Status", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
